// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokyBack.Shared.Infrastructure.Persistence;

#nullable disable

namespace PokyBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250426164047_RemovedRoomNavigation")]
    partial class RemovedRoomNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIME");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EventCode");

                    b.Property<string>("RoomCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("RoomCode");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserUuid");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .HasDatabaseName("IX_Logs_RoomCode");

                    b.HasIndex("RoomId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIME");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedByUuid");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("DeletedOn");

                    b.Property<bool>("IsRevealed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRevealed");

                    b.Property<string>("Topic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None")
                        .HasColumnName("Topic");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("rooms_code_index");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.RoomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int?>("CurrentPick")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentPick");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("JoinedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RoomCode");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("Uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode");

                    b.ToTable("RoomUsers", (string)null);
                });

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.Log", b =>
                {
                    b.HasOne("PokyBack.Shared.Core.Entities.Room", null)
                        .WithMany("Logs")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.RoomUser", b =>
                {
                    b.HasOne("PokyBack.Shared.Core.Entities.Room", "Room")
                        .WithMany("RoomUsers")
                        .HasForeignKey("RoomCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RoomUsers_RoomsCode_fk");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PokyBack.Shared.Core.Entities.Room", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("RoomUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
